### ISSUE TITLE
[FR] - accept application/json as content type

### ISSUE THREAD

**Issue by Keimeno** [interaapps/punyshort#1]
The punyshort API v2 currently only accepts `application/x-www-form-urlencoded` and `multipart/form-data` as content types at route: `/short`.

It currently returns the error id `2`.

**Comment by Keimeno** [comment]
@JulianFun123

**Comment by JulianFun123** [comment]
Sorry, I'll fix it soon

**Comment by JulianFun123** [comment]
Should work now
